### PR TITLE
Use C# 10 features via editorconfig

### PR DESCRIPTION
**Pull request by daniel-rck**
# New Pull Request

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

Please make sure you can check the following boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project
- [x] All new and existing tests passed

### Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] Introduce new language features

### Description

As mentioned in the [official language reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces), "file scoped namespaces" reduce nesting and improves readability. I added an `.editorconfig` file with the recommended formatting options and also did some nuget updates.

### CODE REVIEW

**Comment by FlorianRappl** [comment]
> As mentioned in the [official language reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces), "file scoped namespaces" reduce nesting and improves readability.

I don't really agree with that. While this might be true in long term it is not true right now - most developers are not familiar with that syntax and it does not work with older compilers.

In general for this PR (which changes *all* files) to be applicable the value add needs to be expressed. Right now I do not see the value add of the PR. Can you elaborate?

**Comment by daniel-rck** [comment]
The statement that "most developers are not familiar with that syntax" is biased - maybe you are right, but my personal opinion is really what I wrote already (readability). Just like "ImplicitUsings", that are used in the DevServer, this is imho state of the art.

In perspective of compatibility only dotnet 6 and 7 are [officially supported](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) right now - so i see no problem supporting only these. But that decision is of course up to you, the maintainer.

**Comment by FlorianRappl** [comment]
> The statement that "most developers are not familiar with that syntax" is biased

Hm I am not sure how that is biased. There are multiple surveys out there - about older states of C# (pre 10) and the result was always the same. The cutting edge features are only known my a small fraction and it takes quite a bit of time until the majority knows the new syntax.

The question about the value add is still out there. As it stands the PR is too massive as it changes all the files. This is a major headache, e.g., to sync with the `blazor-7.0` and maybe other branches in the future.

So if there is some value add in this PR my recommendation is to condense the PR to such details first.

> In perspective of compatibility only dotnet 6 and 7 are [officially supported](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) right now - so i see no problem supporting only these. But that decision is of course up to you, the maintainer.

Not sure I get that comment. Can you elaborate? I was referring to older versions of the C# language / compiler, which is not related to the version of the runtime.

**Comment by daniel-rck** [comment]
Besides the new language features there is no "value" added, so if you don't agree with that the PR would be obsolete.

I didn't have the older compilers in mind, more the runtime.

**Pull request closed without merging**
