### PR TITLE
add support for multiple page parameters

### PR DESCRIPTION
**Pull request by luckyluggi**
# New Pull Request

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

Please make sure you can check the following boxes:

- [ ] I have read the **CONTRIBUTING** document
- [ ] My code follows the code style of this project
- [ ] All new and existing tests passed

### Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [x] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes

### Description

[Place a meaningful description here]
this should add support for multiple routes in one page

### Remarks

[Optionally place any follow-up comments, remarks, observations, or notes here for future reference]

### CODE REVIEW

**Comment by luckyluggi** [comment]
Hy @FlorianRappl. Please do not jet approve tihis. I Think this should do it, but i dont really know hot to test the piral.Core package locally. Where is it actually referenced?

**Comment by FlorianRappl** [comment]
Piral.Core is never referenced - it is packaged into `blazor` (npm package) to form the basis for an app shell or standalone pilet.

Piral.Core represents the Blazor entry point / application. In the end this drives the rendering process and forms the Blazor orchestration layer from the perspective of Piral.

**Comment by FlorianRappl** [comment]
Once we fix the build (https://smapiot.visualstudio.com/piral-pipelines/_build/results?buildId=4324&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=f8ed7bd8-2a7f-56f6-9385-7fc29a8b5b7b) we can also just ship it and test it then.

Personally, in such cases I always build locally and then replace the assemblies of, e.g., the example project (or any project) with the build artifacts. But I have no problem using the preview version for it - as long as we have enough reason to believe that this might already work.

**Comment by luckyluggi** [comment]
ok. we could try it now. or do you see room for improvement?

**Review by FlorianRappl — APPROVED** [review]
LGTM - thanks!

**Comment by FlorianRappl** [comment]
Let's give it a try!

**Pull request merged**
