### PR TITLE
fix out of range error

### PR DESCRIPTION
**Pull request by luckyluggi**
# New Pull Request

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

Please make sure you can check the following boxes:

- [ ] I have read the **CONTRIBUTING** document
- [ ] My code follows the code style of this project
- [ ] All new and existing tests passed

### Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes

### Description
This fixes an error in the last PR
[Place a meaningful description here]

### Remarks

[Optionally place any follow-up comments, remarks, observations, or notes here for future reference]

### CODE REVIEW

**Comment by luckyluggi** [comment]
I tried testing it locally by building the Prial.Blazor.Core pacckage and then copying "...\Piral.Blazor\src\Piral.Blazor.Core\bin\Debug\net6.0\Piral.Blazor.Core.dll" (and Piral.Blazor.Core.pdb) over to "...\piral~\MyPilet\node_modules\@myorg\myshell\app\_framework", but it didnt work. Do i need to copy it somewhere else?

**Review by FlorianRappl — APPROVED** [review]
LGTM - thanks for spotting!

**Comment by FlorianRappl** [comment]
Just copying the dll is not enough. Blazor uses the info in the adjacent json (blazor.boot.json or so) to actually know what is there. Important part is the SHA.

**Comment by luckyluggi** [comment]
> Just copying the dll is not enough. Blazor uses the info in the adjacent json (blazor.boot.json or so) to actually know what is there. Important part is the SHA.

Ah thx. Now it's working.
But the new version is not jet published on npm. does it really take that long?

**Comment by luckyluggi** [comment]
ah now its here.

**Pull request merged**
